### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by verlok**
Hello Jeremy, I've fixed some typos I've found while following this today with my workmates

### CODE REVIEW

**Comment by nucliweb** [comment]
Be careful; you are changing all the links from `malchata` to `verlok`

**Comment by verlok** [comment]
Wtf, I didn't mean to do it here in the master repo, but only in my fork! 
How did this happen?

**Comment by verlok** [comment]
Ah, I know what's the issue here, this PR was from my `main` branch to this `main`, instead of from a branch where I was only fixing the typos. 

I will close this PR. 
And I will not open a new one, as there seemed to be no interest in fixing the typos.

**Comment by verlok** [comment]
Thanks for the heads up Joan! 
@nucliweb

**Pull request closed without merging**
